# Generated by Django 3.1.5 on 2021-09-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Type_of_Association',
                'verbose_name_plural': 'Type_of_Associations',
            },
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('location', models.CharField(max_length=256, verbose_name='location')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=255, verbose_name='phone_number')),
                ('association_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_type', to='associations.type_of_association')),
                ('grouped_events', models.ManyToManyField(related_name='events', to='events.Grouped_Events')),
                ('single_events', models.ManyToManyField(related_name='single_events', to='events.Single_Event')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
            },
        ),
    ]
