# Generated by Django 3.1.5 on 2021-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_proto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('venue', models.CharField(max_length=150, verbose_name='venue')),
                ('organiser_phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='organiser_phone_number')),
                ('starting_time', models.TimeField(verbose_name='startin_time')),
                ('closing_time', models.TimeField(verbose_name='closing_time')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('fee', models.FloatField(blank=True, default=0.0, verbose_name='fee')),
            ],
            options={
                'verbose_name': 'Event_proto',
                'verbose_name_plural': 'Event_protos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('event_list', models.ManyToManyField(related_name='event_lists', to='events.Event_proto')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
