# Generated by Django 3.1.5 on 2021-09-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.SlugField(default='null')),
                ('description', models.TextField()),
                ('keywords', models.CharField(default='null', max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('image_source', models.CharField(blank=True, max_length=255, null=True)),
                ('image_description', models.CharField(blank=True, default='image', max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('references', models.TextField(blank=True, default='null', null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='sets.level')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-pub_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sub_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_section_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source', models.CharField(blank=True, max_length=255, null=True)),
                ('image_description', models.CharField(blank=True, default='image', max_length=255)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_section', to='articles.article')),
            ],
            options={
                'verbose_name': 'Sub_Section',
                'verbose_name_plural': 'Sub_Sections',
                'ordering': ['pub_date'],
            },
        ),
    ]
