from events.serializers import Single_Event_Serializer, Grouped_Events_Serializer
from events.serializers import Single_Event, Grouped_Events
from rest_framework import permissions,generics,status
from rest_framework.response import Response