from examinations.serializers import Examination_Serializer, Exam_day_and_venue_Serializer
from examinations.models import Examination, Exam_day_and_venue
from rest_framework import permissions,generics,status
from rest_framework.response import Response