# Generated by Django 3.1.5 on 2021-09-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security_Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='edited')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('confirmation', models.FloatField(default=0.0, verbose_name='confirmation')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Security_Alert',
                'verbose_name_plural': 'Security_Alerts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Security_alert_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Security_alert_type',
                'verbose_name_plural': 'Security_alert_types',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
