# Generated by Django 3.1.5 on 2021-09-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=150, verbose_name='day')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recommended_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('author', models.CharField(max_length=150, verbose_name='author')),
                ('publisher', models.CharField(max_length=150, verbose_name='publisher')),
                ('volume', models.CharField(blank=True, default=1, max_length=150, verbose_name='volume')),
                ('year_of_publication', models.CharField(max_length=150, verbose_name='year_of_publication')),
            ],
            options={
                'verbose_name': 'Recommended_text',
                'verbose_name_plural': 'Recommended_texts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lecture_day_and_venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField(verbose_name='startin_time')),
                ('closing_time', models.TimeField(verbose_name='closing_time')),
                ('venue', models.CharField(max_length=150)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_day', to='lectures.day')),
            ],
            options={
                'verbose_name': 'Lecture_day_and_venue',
                'verbose_name_plural': 'Lectures_days_and_venues',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField()),
                ('course_title', models.CharField(max_length=150, verbose_name='course_title')),
                ('Lecturers_in_charge', models.CharField(blank=True, max_length=250, null=True, verbose_name='lecturers_in_charge')),
                ('Recommended_text', models.ManyToManyField(related_name='recommended_text', to='lectures.Recommended_text')),
                ('days_and_venues', models.ManyToManyField(related_name='lecture_days_and_venues', to='lectures.Lecture_day_and_venue')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
