# Generated by Django 3.1.5 on 2021-09-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('departments', '0001_initial'),
        ('events', '0001_initial'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=150, verbose_name='year')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='departments.department')),
                ('exams', models.ManyToManyField(related_name='examination', to='examinations.Examination')),
                ('grouped_events', models.ManyToManyField(related_name='grouped_events', to='events.Grouped_Events')),
                ('lectures', models.ManyToManyField(related_name='lecture', to='lectures.Lecture')),
                ('single_events', models.ManyToManyField(related_name='single_event', to='events.Single_Event')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='name')),
                ('department_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='departments.department')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'managed': True,
            },
        ),
    ]
