# Generated by Django 3.1.5 on 2021-09-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('location', models.CharField(max_length=150, verbose_name='name')),
                ('grouped_events', models.ManyToManyField(related_name='institution_events', to='events.Grouped_Events')),
                ('single_events', models.ManyToManyField(related_name='institution_single_events', to='events.Single_Event')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
