# Generated by Django 3.1.5 on 2021-09-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_day_and_venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField(verbose_name='startin_time')),
                ('closing_time', models.TimeField(verbose_name='closing_time')),
                ('venue', models.CharField(max_length=150)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_day', to='lectures.day')),
            ],
            options={
                'verbose_name': 'Exam_day_and_venue',
                'verbose_name_plural': 'Exam_days_and_venues',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField()),
                ('course_title', models.CharField(max_length=150, verbose_name='course_title')),
                ('invigilators', models.CharField(blank=True, max_length=250, null=True, verbose_name='invigilators')),
                ('days_and_venues', models.ManyToManyField(related_name='exam_day_and_venue', to='examinations.Exam_day_and_venue')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
